/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "outline-variant": "#ddc0ba",
        "inverse-surface": "#30312e",
        "secondary-fixed-dim": "#b5ccc1",
        "on-surface-variant": "#56423e",
        "secondary": "#4e635a",
        "secondary-container": "#cee5da",
        "surface-container": "#efeeea",
        "on-primary-container": "#5a0d02",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#8e4e14",
        "on-secondary-container": "#52675e",
        "tertiary-fixed": "#ffdcc4",
        "inverse-on-surface": "#f2f0ed",
        "surface": "#fbf9f5",
        "on-background": "#1b1c1a",
        "secondary-fixed": "#d1e8dd",
        "on-tertiary-fixed-variant": "#6f3800",
        "surface-tint": "#9f402d",
        "surface-container-low": "#f5f3ef",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#802918",
        "background": "#fbf9f5",
        "on-secondary-fixed-variant": "#374b43",
        "on-primary-fixed": "#3e0500",
        "primary-container": "#e2725b",
        "on-error-container": "#93000a",
        "primary": "#9f402d",
        "surface-dim": "#dbdad6",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#ffb780",
        "on-surface": "#1b1c1a",
        "tertiary-container": "#cc8143",
        "on-primary": "#ffffff",
        "surface-container-high": "#eae8e4",
        "primary-fixed-dim": "#ffb4a5",
        "surface-variant": "#e4e2de",
        "on-tertiary-fixed": "#2f1400",
        "surface-bright": "#fbf9f5",
        "primary-fixed": "#ffdad3",
        "inverse-primary": "#ffb4a5",
        "on-tertiary": "#ffffff",
        "outline": "#89726d",
        "on-tertiary-container": "#472200",
        "surface-container-highest": "#e4e2de",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#0b1f18"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "card-padding": "32px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "display-lg": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "display-lg-mobile": ["40px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      },
      boxShadow: {
        soft: "0 14px 40px rgba(17, 24, 39, 0.08)",
      },
    },
  },
  plugins: [],
};
